package model.input;

import model.Agent;
import model.Map;
import model.XY;

public abstract class GetPosition extends Input {

	public enum Position {
		LEFT, UP, DOWN, RIGHT, CURRENT, PRIMARY, SECONDARY, PREVIOUS, XY_VALUE, 
		
		ENEMY_SPEED_HIGH, ENEMY_SPEED_LOW, ENEMY_POWER_HIGH, ENEMY_POWER_LOW, ENEMY_DISTANCE_HIGH, ENEMY_DISTANCE_LOW, ENEMY_HEALTH_HIGH, ENEMY_HEALTH_LOW, ENEMY_MAXHEALTH_HIGH, ENEMY_MAXHEALTH_LOW, ENEMY_EXP_HIGH, ENEMY_EXP_LOW, ENEMY_AGE_HIGH, ENEMY_AGE_LOW, 
		
		ALLY_SPEED_HIGH, ALLY_SPEED_LOW, ALLY_POWER_HIGH, ALLY_POWER_LOW, ALLY_DISTANCE_HIGH, ALLY_DISTANCE_LOW, ALLY_HEALTH_HIGH, ALLY_HEALTH_LOW, ALLY_MAXHEALTH_HIGH, ALLY_MAXHEALTH_LOW, ALLY_EXP_HIGH, ALLY_EXP_LOW, ALLY_AGE_HIGH, ALLY_AGE_LOW
	};

	public abstract XY getPosition(Agent agent, Map map);
}
